### ISSUE TITLE
1.81pr1 crash on open inventory

### ISSUE THREAD

**Issue by kreezxil** [MinecraftModDevelopmentMods/Computality#1]
all I did was hit 'e'

https://gist.github.com/kreezxil/c14ec28b742d9374721f2e59e836d2f7

**Comment by TheCodedOne** [comment]
I'm not sure why this is happening, i'll try fix it, for now [1.81pr0](https://minecraft.curseforge.com/projects/computality/files/2415040) should work.

**Comment by TheCodedOne** [comment]
Solved in 99cc691 will push a bugfix update to curse now

**Comment by TheCodedOne** [comment]
https://minecraft.curseforge.com/projects/computality/files/2415476
